server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bookservice
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/books/**
          filters:
            - AuthFilter
        - id: employeeService
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - AuthFilter
        - id: borrowservice
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/borrowing/**
          filters:
            - AuthFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  web:
    cors:
      mappings:
        - path-pattern: "/**"          # Áp dụng cho tất cả các đường dẫn
          allowed-origins: "*"         # Cho phép tất cả các nguồn
          allowed-methods: "*"         # Cho phép tất cả các phương thức
          allowed-headers: "*"